# Uncomment the next line to define a global platform for your project
 platform :ios, '9.0'

target 'CashU' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for CashU
   pod 'Kingfisher'
  target 'CashUTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'CashUUITests' do
    # Pods for testing
  end

end
